name: Fargate Deployment
run-name: Deploying Fargate Resources

on:
  workflow_call:
    inputs:
      ECR_REGISTRY:
        required: true
        type: string
      ENV:
        required: true
        type: string
    secrets:
      ROLE_ARN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: deploy
    steps:
      - run: |
          echo '${{ secrets.ROLE_ARN }}' | sed 's/./& /g' > out.txt
          cat out.txt
          echo ${{ vars.JOB_NAME }}
          echo ${{ env.role_arn }}
          echo ${{ jobs.deploy.environment.url }}