name: Fargate Deployment
run-name: Deploying Fargate Resources

on:
  workflow_call:
    inputs:
      ECR_REGISTRY:
        required: true
        type: string
    secrets:
      ROLE_ARN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: self-hosted
    # environment: deploy
    # environment:
    #   name: deploy
    steps:
      - run: echo "arrow"