---
name: main

on:
    workflow_dispatch:
    push:

# env:
#   ECR_REGISTRY: ghecr
#   ECR_REPOSITORY: test

permissions:
    contents: write
    id-token: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      docker: ${{ steps.filter.outputs.docker }}

    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docker:
              - 'docker/**'

    # secret-scanning:
    #     name: Secret Scan
    #     uses: bayer-int/actions-workflows/.github/workflows/secret-scanning.yml@main

    # linting:
    #     name: Linting
    #     uses: ./.github/workflows/linting.yaml

  deploy:
    # if: ${{ github.ref == 'refs/heads/dev' }}
    if: ${{ needs.changes.outputs.docker == 'true' }}
    needs: changes
    uses: ./.github/workflows/fargate.yaml
    secrets: inherit
    with:
        ECR_REGISTRY: ghecr
        ECR_REPOSITORY: test
        ACCOUNT_ID: 525524992861

    # validate:
    #     if: ${{ github.ref != 'refs/heads/main' }}
    #     uses: ./.github/workflows/validate.yaml
    #     needs: [linting]
    #     secrets: inherit
    #     with:
    #         # It could have been a workflow environment variable, but:
    #         # https://github.com/orgs/community/discussions/25295
    #         TERRAFORM_CORE_VERSION: 1.6.1