---
name: main

on:
    workflow_dispatch:
    push:

# env:
#   ECR_REGISTRY: ghecr
#   ECR_REPOSITORY: test

permissions:
    contents: write
    id-token: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      docker: ${{ steps.filter.outputs.docker }}
      docker-matrix: ${{ steps.docker-matrix.outputs.value }}

    environment:
     name: dev

    steps:
      - run: |
          echo "Environment name: $env"

      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docker:
              - 'docker/**'

      - uses: tj-actions/changed-files@v44
        id: docker-changed-dirs
        with:
          dir_names: "true"
          files: docker/**/src/**

      - id: docker-matrix
        run: |
          echo "${{ steps.docker-changed-dirs.outputs.all_changed_files }}"
          echo "${{ steps.docker-changed-dirs.outputs.all_changed_files }}" | sed 's/docker\///g' | sed 's/ /", "/g' | sed 's/.*/value=["&"]/' >> $GITHUB_OUTPUT

    # secret-scanning:
    #     name: Secret Scan
    #     uses: bayer-int/actions-workflows/.github/workflows/secret-scanning.yml@main

    # linting:
    #     name: Linting
    #     uses: ./.github/workflows/linting.yaml

  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello"

  deploy:
    # if: ${{ github.ref == 'refs/heads/dev' }}
    if: ${{ needs.changes.outputs.docker == 'true' }}
    needs: changes
    uses: ./.github/workflows/fargate.yaml
    secrets: inherit
    strategy:
      matrix:
        task: ${{fromJSON(needs.changes.outputs.docker-matrix)}}
    with:
        ECR_REGISTRY: ghecr
        ECR_REPOSITORY: test
        ACCOUNT_ID: 525524992861
        CLUSTER_NAME: ghecr-ECSFargateCluster-hcCeInCKWmcR
        TASK_DEFINITION: fargate-task
        TASK: ${{ matrix.task }}

    # validate:
    #     if: ${{ github.ref != 'refs/heads/main' }}
    #     uses: ./.github/workflows/validate.yaml
    #     needs: [linting]
    #     secrets: inherit
    #     with:
    #         # It could have been a workflow environment variable, but:
    #         # https://github.com/orgs/community/discussions/25295
    #         TERRAFORM_CORE_VERSION: 1.6.1